name: Help me!
description: If you need help using the engine.\nIf your issue is with compiling, ensure you are on haxe 4.3.6 or newer and using the haxelibs set listed in .hxpkg
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true

  - type: dropdown
    id: modding
    attributes:
      label: "Are you modding a build from source or with scripting?"
      options:
        - Scripting
        - Source
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows x64"
        - "Linux"
        - "Mac"
        - "HashLink, or other build system"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: false
