# FUCK MY LIFE BROOOOOOOOO.
name: Binaries

on: # Workflow triggers on both when a commit is pushed, or when a pull request is made.
    push:
        branches: 
            - main 
            - dev
    pull_request:
        branches:
            - main
            - dev
    
    workflow_dispatch: # Run workflow manually from the actions tab.
    workflow_call: #For release builds
        inputs:
            buildFlags:
                required: false
                type: string


jobs: # FUCK MY LIFE BROOOOO
    Windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v6.0.2
            - uses: krdlab/setup-haxe@master

              with: 
                haxe-version: 4.3.7

            - name: Install libs
              run: |
                haxelib setup C:/haxelib
                haxelib install hxcpp > nul --quiet
                haxelib install hxpkg --quiet
                haxelib run hxpkg install
                haxelib run lime rebuild cpp
            - name: Compile build
              run: haxelib run lime build windows -D ${{inputs.buildFlags}}
            - name: Publish artifact
              uses: actions/upload-artifact@v7.0.0
              with:
                name: NightmareVision (Windows)
                path: export/release/windows/bin
    #
    Linux:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v6.0.2
            - uses: krdlab/setup-haxe@master

              with:
                haxe-version: 4.3.7
            
            - name: Install LibVLC
              run: |
                sudo apt-get install vlc libvlc-dev libvlccore-dev vlc-bin
            - name: Install libs
              run: |
                haxelib setup ~/haxelib
                haxelib install hxcpp > /dev/null --quiet
                haxelib install hxpkg --quiet
                haxelib run hxpkg install
            - name: Compile build
              run: haxelib run lime build Project.xml linux -D ${{inputs.buildFlags}}
            - name: Publish artifact
              uses: actions/upload-artifact@v7.0.0
              with:
                name: NightmareVision (Linux)
                path: 'export/release/linux/bin'
